title: EVOTOR CENTER - Центр помощи предпринимателям
name: EVOTOR CENTER
description: Продажа онлайн кассы, бухгалтерские услуги, электронно цифровая подпись
themecolor: '#202225'
imagehome: img/evotorcenter.jpg
url: 'http://evotorcenter.ru'
baseurl: '/'

plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 9
  title: 'title - Страница :num'
  limit: 0
  sort_field: 'date'
  trail:
    before: 2
    after: 2

exclude: ['node_modules', 'gulpfile.js', 'package-lock.json', 'js/common.js', 'npm-dubug.log', '**/Thumbs.db', 'libs', 'sass']
soc:
  <li><a href="#"><i class="fa fa-vk"></i></a></li>
  <li><a href="#"><i class="fa fa-odnoklassniki"></i></a></li>
  <li><a href="#"><i class="fa fa-instagram"></i></a></li>    

copyright: webartstudio
  


